### ISSUE TITLE
Key format ed25519

### ISSUE THREAD

**Issue by r-wenger** [RS-DAT/JupyterDaskOnSLURM#53]
Hi , here is my error probably due to the key size :

`
Do you want to install all components on remote host? (Y/n): y
Unknown exception: q must be exactly 160, 224, or 256 bits long
Traceback (most recent call last):
  File "/Users/rwenger/miniconda3/envs/HDCRS/lib/python3.10/site-packages/paramiko/transport.py", line 2163, in run
    handler(self.auth_handler, m)
  File "/Users/rwenger/miniconda3/envs/HDCRS/lib/python3.10/site-packages/paramiko/auth_handler.py", line 395, in _parse_service_accept
    sig = self.private_key.sign_ssh_data(blob, algorithm)
  File "/Users/rwenger/miniconda3/envs/HDCRS/lib/python3.10/site-packages/paramiko/dsskey.py", line 109, in sign_ssh_data
    key = dsa.DSAPrivateNumbers(
  File "/Users/rwenger/miniconda3/envs/HDCRS/lib/python3.10/site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 242, in private_key
    return ossl.load_dsa_private_numbers(self)
  File "/Users/rwenger/miniconda3/envs/HDCRS/lib/python3.10/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 876, in load_dsa_private_numbers
    dsa._check_dsa_private_numbers(numbers)
  File "/Users/rwenger/miniconda3/envs/HDCRS/lib/python3.10/site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 283, in _check_dsa_private_numbers
    _check_dsa_parameters(parameters)
  File "/Users/rwenger/miniconda3/envs/HDCRS/lib/python3.10/site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 275, in _check_dsa_parameters
    raise ValueError("q must be exactly 160, 224, or 256 bits long")
ValueError: q must be exactly 160, 224, or 256 bits long

Traceback (most recent call last):
  File "/Users/rwenger/Documents/HDCRS/JupyterDaskOnSLURM-workshops/runJupyterDaskOnSLURM.py", line 459, in <module>
    main()
  File "/Users/rwenger/Documents/HDCRS/JupyterDaskOnSLURM-workshops/runJupyterDaskOnSLURM.py", line 427, in main
    install = installJDOnSLURM.install_JD(config_inputs, platform_name, envfile = 'environment.yaml')
  File "/Users/rwenger/Documents/HDCRS/JupyterDaskOnSLURM-workshops/installJDOnSLURM.py", line 169, in install_JD
    folder_exists = ssh_remote_executor(config_inputs, check_clone)
  File "/Users/rwenger/Documents/HDCRS/JupyterDaskOnSLURM-workshops/runJupyterDaskOnSLURM.py", line 210, in ssh_remote_executor
    result = func(conn, *inargs)
  File "/Users/rwenger/Documents/HDCRS/JupyterDaskOnSLURM-workshops/installJDOnSLURM.py", line 42, in check_clone
    result = conn.run(cmd, hide=True)
  File "/Users/rwenger/miniconda3/envs/HDCRS/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/Users/rwenger/miniconda3/envs/HDCRS/lib/python3.10/site-packages/fabric/connection.py", line 26, in opens
    self.open()
  File "/Users/rwenger/miniconda3/envs/HDCRS/lib/python3.10/site-packages/fabric/connection.py", line 642, in open
    self.client.connect(**kwargs)
  File "/Users/rwenger/miniconda3/envs/HDCRS/lib/python3.10/site-packages/paramiko/client.py", line 459, in connect
    self._auth(
  File "/Users/rwenger/miniconda3/envs/HDCRS/lib/python3.10/site-packages/paramiko/client.py", line 706, in _auth
    self._transport.auth_publickey(username, key)
  File "/Users/rwenger/miniconda3/envs/HDCRS/lib/python3.10/site-packages/paramiko/transport.py", line 1640, in auth_publickey
    return self.auth_handler.wait_for_response(my_event)
  File "/Users/rwenger/miniconda3/envs/HDCRS/lib/python3.10/site-packages/paramiko/auth_handler.py", line 245, in wait_for_response
    raise e
  File "/Users/rwenger/miniconda3/envs/HDCRS/lib/python3.10/site-packages/paramiko/transport.py", line 2163, in run
    handler(self.auth_handler, m)
  File "/Users/rwenger/miniconda3/envs/HDCRS/lib/python3.10/site-packages/paramiko/auth_handler.py", line 395, in _parse_service_accept
    sig = self.private_key.sign_ssh_data(blob, algorithm)
  File "/Users/rwenger/miniconda3/envs/HDCRS/lib/python3.10/site-packages/paramiko/dsskey.py", line 109, in sign_ssh_data
    key = dsa.DSAPrivateNumbers(
  File "/Users/rwenger/miniconda3/envs/HDCRS/lib/python3.10/site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 242, in private_key
    return ossl.load_dsa_private_numbers(self)
  File "/Users/rwenger/miniconda3/envs/HDCRS/lib/python3.10/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 876, in load_dsa_private_numbers
    dsa._check_dsa_private_numbers(numbers)
  File "/Users/rwenger/miniconda3/envs/HDCRS/lib/python3.10/site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 283, in _check_dsa_private_numbers
    _check_dsa_parameters(parameters)
  File "/Users/rwenger/miniconda3/envs/HDCRS/lib/python3.10/site-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 275, in _check_dsa_parameters
    raise ValueError("q must be exactly 160, 224, or 256 bits long")
ValueError: q must be exactly 160, 224, or 256 bits long
`

**Comment by cpranav93** [comment]
Does your key have an associated passphrase? Currently RSDAT only supports keys with no passphrase which provide access to the remote host without additional input.

**Comment by r-wenger** [comment]
Oh yeah that's it i have a passphrase ... thank you for your time !
