### ISSUE TITLE
mamba crash during --mode install

### ISSUE THREAD

**Issue by Simon-van-Diepen** [RS-DAT/JupyterDaskOnSLURM#54]
When running python3 runJupyterDaskOnSLURM.py --uid <UID> --mode install (with my UID) the installation starts fine, the directories are cloned, I accepted the mamba terms. During the activation of mamba I got this error.

Manual installation of mamba worked afterwards, but not via --mode install. 

``` 
To install conda's shell functions for easier access, first activate, then:

conda init

If you'd prefer that conda's base environment not be activated on startup, 
   set the auto_activate_base parameter to false: 

conda config --set auto_activate_base false

Thank you for installing Mambaforge!
Traceback (most recent call last):
  File "/Users/sanvandiepen/Documents/JupyterDaskOnSLURM/runJupyterDaskOnSLURM.py", line 463, in <module>
    main()
  File "/Users/sanvandiepen/Documents/JupyterDaskOnSLURM/runJupyterDaskOnSLURM.py", line 431, in main
    install = installJDOnSLURM.install_JD(config_inputs, platform_name, envfile = 'environment.yaml')
  File "/Users/sanvandiepen/Documents/JupyterDaskOnSLURM/installJDOnSLURM.py", line 185, in install_JD
    env_exists, envname = ssh_remote_executor(config_inputs, test_env, envfile)
  File "/Users/sanvandiepen/Documents/JupyterDaskOnSLURM/runJupyterDaskOnSLURM.py", line 210, in ssh_remote_executor
    result = func(conn, *inargs)
  File "/Users/sanvandiepen/Documents/JupyterDaskOnSLURM/installJDOnSLURM.py", line 91, in test_env
    result = conn.run(cmd, hide=True)
  File "/Users/sanvandiepen/Library/Python/3.9/lib/python/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/Users/sanvandiepen/Library/Python/3.9/lib/python/site-packages/fabric/connection.py", line 27, in opens
    return method(self, *args, **kwargs)
  File "/Users/sanvandiepen/Library/Python/3.9/lib/python/site-packages/fabric/connection.py", line 739, in run
    return self._run(self._remote_runner(), command, **kwargs)
  File "/Users/sanvandiepen/Library/Python/3.9/lib/python/site-packages/invoke/context.py", line 113, in _run
    return runner.run(command, **kwargs)
  File "/Users/sanvandiepen/Library/Python/3.9/lib/python/site-packages/fabric/runners.py", line 75, in run
    return super().run(command, **kwargs)
  File "/Users/sanvandiepen/Library/Python/3.9/lib/python/site-packages/invoke/runners.py", line 395, in run
    return self._run_body(command, **kwargs)
  File "/Users/sanvandiepen/Library/Python/3.9/lib/python/site-packages/invoke/runners.py", line 451, in _run_body
    return self.make_promise() if self._asynchronous else self._finish()
  File "/Users/sanvandiepen/Library/Python/3.9/lib/python/site-packages/invoke/runners.py", line 518, in _finish
    raise UnexpectedExit(result)
invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!

Command: 'cd ~/JupyterDaskOnSLURM && head -1 environment.yaml && mamba env list'

Exit code: 127

Stdout:

name: jupyter_dask

Stderr:


 * keychain 2.8.5 ~ http://www.funtoo.org
 * Found existing ssh-agent: <SSH AGENT NUMBER>
 * Warning: can't find bitbucket_spider; skipping

bash: mamba: command not found
```

**Comment by cpranav93** [comment]
@Simon-van-Diepen, during mamba installation one of the prompts would have been on whether to run conda init yes/no. Do you know what you selected?

The error here occurs because mamba got installed but it was not initialized with the mamba init command which makes it visible to the bash command line.

**Comment by Simon-van-Diepen** [comment]
I selected yes on that prompt
